// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeGosZa_3E0yuUinc1Wm4CU5qIsPHBAUc',
    appId: '1:13493655129:web:4c4a16aca12bf6d9220348',
    messagingSenderId: '13493655129',
    projectId: 'fir-flutter-app-76323',
    authDomain: 'fir-flutter-app-76323.firebaseapp.com',
    storageBucket: 'fir-flutter-app-76323.appspot.com',
    measurementId: 'G-FTBHRXBNRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76aNJ-s0Lu47FrkK1Jh608ojMFcnFV0I',
    appId: '1:13493655129:android:b1f399bc73a0526b220348',
    messagingSenderId: '13493655129',
    projectId: 'fir-flutter-app-76323',
    storageBucket: 'fir-flutter-app-76323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8eJP0PjVhF4m6Mzk5spH73sSLf4MWF4E',
    appId: '1:13493655129:ios:88429809353fdcde220348',
    messagingSenderId: '13493655129',
    projectId: 'fir-flutter-app-76323',
    storageBucket: 'fir-flutter-app-76323.appspot.com',
    iosClientId: '13493655129-ghn7n3621da0jsfjcmq0onre8p1qubfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8eJP0PjVhF4m6Mzk5spH73sSLf4MWF4E',
    appId: '1:13493655129:ios:092e6bfabf400d38220348',
    messagingSenderId: '13493655129',
    projectId: 'fir-flutter-app-76323',
    storageBucket: 'fir-flutter-app-76323.appspot.com',
    iosClientId: '13493655129-qoabtkt3i7dh7rmjsteuf1io16hjrfkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfirebaseapp.RunnerTests',
  );
}
